spring:
  #profiles:
  #active: dev
  application:
    name: wecare
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
  jackson:
    time-zone: Asia/Seoul
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.core.env: DEBUG

springdoc:
  api-docs:
    path: /api/api-spec
    enabled: true
  swagger-ui:
    path: /api/my-docs
    enabled: true
  override-with-generic-response: false
  use-fqn: true